const cfg=window.NOORA_SUPABASE;const client=window.supabase.createClient(cfg.url,cfg.publishableKey);const $=s=>document.querySelector(s);const allowedAdminEmail="manomalik3817@gmail.com";const statuses=["Pending","Contacted","Confirmed","Processing","Shipped","Completed","Cancelled"];
function message(text,error=false){const el=$("#adminMessage");el.textContent=text;el.className="admin-message"+(error?" error":"")}
function safeCell(text){const el=document.createElement("span");el.textContent=text??"—";return el}
function addTextCell(row,text,cls=""){const td=document.createElement("td");if(cls)td.className=cls;td.appendChild(safeCell(text));row.appendChild(td);return td}
async function loadOrders(){message("Loading orders…");const {data,error}=await client.from("orders").select("id,created_at,customer_name,customer_phone,customer_email,delivery_address,city,product_name,product_size,quantity,total_amount,payment_method,order_status").order("created_at",{ascending:false}).limit(500);if(error){message("Could not load requests. Check the SQL/RLS setup and admin login.",true);return}const body=$("#ordersBody");body.replaceChildren();$("#orderCount").textContent=`${data.length} request${data.length===1?"":"s"}`;if(!data.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=6;td.className="empty-row";td.textContent="No customer requests yet.";tr.appendChild(td);body.appendChild(tr)}
for(const order of data){const tr=document.createElement("tr");const orderTd=document.createElement("td");orderTd.append(safeCell(`#${order.id}`));const date=document.createElement("div");date.className="order-meta";date.textContent=order.created_at?new Date(order.created_at).toLocaleString():"";orderTd.appendChild(date);tr.appendChild(orderTd);
const customer=document.createElement("td");customer.append(safeCell(order.customer_name));const meta=document.createElement("div");meta.className="order-meta";meta.textContent=[order.customer_phone,order.customer_email].filter(Boolean).join(" · ");customer.appendChild(meta);tr.appendChild(customer);
const item=document.createElement("td");item.append(safeCell(order.product_name));const size=document.createElement("div");size.className="order-meta";size.textContent=`Size: ${order.product_size||"Not specified"} · Qty: ${order.quantity??1}`;item.appendChild(size);tr.appendChild(item);
const delivery=document.createElement("td");delivery.append(safeCell(order.city||"—"));const addr=document.createElement("div");addr.className="order-meta";addr.textContent=order.delivery_address||"Address not provided";delivery.appendChild(addr);const pay=document.createElement("div");pay.className="order-meta";pay.textContent=order.payment_method||"Payment not decided";delivery.appendChild(pay);tr.appendChild(delivery);
const statusTd=document.createElement("td"),select=document.createElement("select");for(const status of statuses){const opt=document.createElement("option");opt.value=status;opt.textContent=status;select.appendChild(opt)}select.value=statuses.includes(order.order_status)?order.order_status:"Pending";statusTd.appendChild(select);tr.appendChild(statusTd);
const updateTd=document.createElement("td"),update=document.createElement("button");update.textContent="Save status";update.addEventListener("click",async()=>{update.disabled=true;const {error}=await client.from("orders").update({order_status:select.value}).eq("id",order.id);update.disabled=false;if(error){message("Status update failed. Check admin RLS policy.",true);return}message(`Request #${order.id} updated to ${select.value}.`)});updateTd.appendChild(update);tr.appendChild(updateTd);body.appendChild(tr)}message("Dashboard loaded.")}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("#loginBtn"),fd=new FormData(e.target);btn.disabled=true;message("Signing in…");const {data,error}=await client.auth.signInWithPassword({email:fd.get("email"),password:fd.get("password")});btn.disabled=false;if(error){message("Sign-in failed. Check your email/password and confirm the admin Auth user exists.",true);return}if(data.user.email?.toLowerCase()!==allowedAdminEmail.toLowerCase()){await client.auth.signOut();message("This account is not authorized for the NOORA admin dashboard.",true);return}e.target.hidden=true;$("#dashboard").hidden=false;await loadOrders()});
$("#refreshBtn").onclick=loadOrders;$("#logoutBtn").onclick=async()=>{await client.auth.signOut();$("#dashboard").hidden=true;$("#loginForm").hidden=false;message("Signed out.")};
